# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the elixir code generator program.
# Do not edit the class manually.

defmodule GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ExclusionRule do
  @moduledoc """
  The rule that specifies conditions when findings of infoTypes specified in
  `InspectionRuleSet` are removed from results.

  ## Attributes

  - dictionary (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2Dictionary.t): Dictionary which defines the rule. Defaults to `nil`.
  - excludeInfoTypes (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ExcludeInfoTypes.t): Set of infoTypes for which findings would affect this rule. Defaults to `nil`.
  - matchingType (String.t): How the rule is applied, see MatchingType documentation for details. Defaults to `nil`.
  - regex (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2Regex.t): Regular expression which defines the rule. Defaults to `nil`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :dictionary => GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2Dictionary.t(),
          :excludeInfoTypes => GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ExcludeInfoTypes.t(),
          :matchingType => String.t(),
          :regex => GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2Regex.t()
        }

  field(:dictionary, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2Dictionary)
  field(:excludeInfoTypes, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ExcludeInfoTypes)
  field(:matchingType)
  field(:regex, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2Regex)
end

defimpl Poison.Decoder, for: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ExclusionRule do
  def decode(value, options) do
    GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ExclusionRule.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ExclusionRule do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
