# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the elixir code generator program.
# Do not edit the class manually.

defmodule GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2AnalyzeDataSourceRiskDetails do
  @moduledoc """
  Result of a risk analysis operation request.

  ## Attributes

  - categoricalStatsResult (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2CategoricalStatsResult.t):  Defaults to `nil`.
  - deltaPresenceEstimationResult (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2DeltaPresenceEstimationResult.t):  Defaults to `nil`.
  - kAnonymityResult (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2KAnonymityResult.t):  Defaults to `nil`.
  - kMapEstimationResult (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2KMapEstimationResult.t):  Defaults to `nil`.
  - lDiversityResult (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2LDiversityResult.t):  Defaults to `nil`.
  - numericalStatsResult (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2NumericalStatsResult.t):  Defaults to `nil`.
  - requestedPrivacyMetric (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2PrivacyMetric.t): Privacy metric to compute. Defaults to `nil`.
  - requestedSourceTable (GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2BigQueryTable.t): Input dataset to compute metrics over. Defaults to `nil`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :categoricalStatsResult =>
            GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2CategoricalStatsResult.t(),
          :deltaPresenceEstimationResult =>
            GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2DeltaPresenceEstimationResult.t(),
          :kAnonymityResult => GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2KAnonymityResult.t(),
          :kMapEstimationResult =>
            GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2KMapEstimationResult.t(),
          :lDiversityResult => GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2LDiversityResult.t(),
          :numericalStatsResult =>
            GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2NumericalStatsResult.t(),
          :requestedPrivacyMetric => GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2PrivacyMetric.t(),
          :requestedSourceTable => GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2BigQueryTable.t()
        }

  field(:categoricalStatsResult,
    as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2CategoricalStatsResult
  )

  field(:deltaPresenceEstimationResult,
    as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2DeltaPresenceEstimationResult
  )

  field(:kAnonymityResult, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2KAnonymityResult)
  field(:kMapEstimationResult, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2KMapEstimationResult)
  field(:lDiversityResult, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2LDiversityResult)
  field(:numericalStatsResult, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2NumericalStatsResult)
  field(:requestedPrivacyMetric, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2PrivacyMetric)
  field(:requestedSourceTable, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2BigQueryTable)
end

defimpl Poison.Decoder, for: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2AnalyzeDataSourceRiskDetails do
  def decode(value, options) do
    GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2AnalyzeDataSourceRiskDetails.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2AnalyzeDataSourceRiskDetails do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
