# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the elixir code generator program.
# Do not edit the class manually.

defmodule GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2CategoricalStatsHistogramBucket do
  @moduledoc """


  ## Attributes

  - bucketSize (String.t): Total number of values in this bucket. Defaults to `nil`.
  - bucketValueCount (String.t): Total number of distinct values in this bucket. Defaults to `nil`.
  - bucketValues (list(GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ValueFrequency.t)): Sample of value frequencies in this bucket. The total number of
  values returned per bucket is capped at 20. Defaults to `nil`.
  - valueFrequencyLowerBound (String.t): Lower bound on the value frequency of the values in this bucket. Defaults to `nil`.
  - valueFrequencyUpperBound (String.t): Upper bound on the value frequency of the values in this bucket. Defaults to `nil`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :bucketSize => String.t(),
          :bucketValueCount => String.t(),
          :bucketValues => list(GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ValueFrequency.t()),
          :valueFrequencyLowerBound => String.t(),
          :valueFrequencyUpperBound => String.t()
        }

  field(:bucketSize)
  field(:bucketValueCount)
  field(:bucketValues, as: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2ValueFrequency, type: :list)
  field(:valueFrequencyLowerBound)
  field(:valueFrequencyUpperBound)
end

defimpl Poison.Decoder,
  for: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2CategoricalStatsHistogramBucket do
  def decode(value, options) do
    GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2CategoricalStatsHistogramBucket.decode(
      value,
      options
    )
  end
end

defimpl Poison.Encoder,
  for: GoogleApi.DLP.V2.Model.GooglePrivacyDlpV2CategoricalStatsHistogramBucket do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
