# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule OpenApi.V2.Model.Operation do
  @moduledoc """


  ## Attributes

  - tags ([String.t]):  Defaults to: `null`.
  - summary (String.t):  Defaults to: `null`.
  - description (String.t):  Defaults to: `null`.
  - externalDocs (ExternalDocumentation):  Defaults to: `null`.
  - operationId (String.t):  Defaults to: `null`.
  - consumes ([String.t]):  Defaults to: `null`.
  - produces ([String.t]):  Defaults to: `null`.
  - parameters ([Parameter]):  Defaults to: `null`.
  - responses (Responses):  Defaults to: `null`.
  - schemes ([String.t]):  Defaults to: `null`.
  - deprecated (boolean()):  Defaults to: `null`.
  - security ([SecurityRequirement]):  Defaults to: `null`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :tags => list(any()),
          :summary => any(),
          :description => any(),
          :externalDocs => OpenApi.V2.Model.ExternalDocumentation.t(),
          :operationId => any(),
          :consumes => list(any()),
          :produces => list(any()),
          :parameters => list(OpenApi.V2.Model.Parameter.t()),
          :responses => OpenApi.V2.Model.Responses.t(),
          :schemes => list(any()),
          :deprecated => any(),
          :security => list(OpenApi.V2.Model.SecurityRequirement.t())
        }

  @derive Jason.Encoder

  field(:tags, type: :list)
  field(:summary)
  field(:description)
  field(:externalDocs, as: OpenApi.V2.Model.ExternalDocumentation)
  field(:operationId)
  field(:consumes, type: :list)
  field(:produces, type: :list)
  field(:parameters, as: OpenApi.V2.Model.Parameter, type: :list)
  field(:responses, as: OpenApi.V2.Model.Responses)
  field(:schemes, type: :list)
  field(:deprecated)
  field(:security, as: OpenApi.V2.Model.SecurityRequirement, type: :list)
end

defimpl Poison.Decoder, for: OpenApi.V2.Model.Operation do
  def decode(value, options) do
    OpenApi.V2.Model.Operation.decode(value, options)
  end
end

defimpl Poison.Encoder, for: OpenApi.V2.Model.Operation do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
