# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule OpenApi.V2.Model.PathItem do
  @moduledoc """


  ## Attributes

  - $ref (String.t):  Defaults to: `null`.
  - get (Operation):  Defaults to: `null`.
  - put (Operation):  Defaults to: `null`.
  - post (Operation):  Defaults to: `null`.
  - delete (Operation):  Defaults to: `null`.
  - options (Operation):  Defaults to: `null`.
  - head (Operation):  Defaults to: `null`.
  - patch (Operation):  Defaults to: `null`.
  - parameters (Parameter):  Defaults to: `null`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :"$ref" => any(),
          :get => OpenApi.V2.Model.Operation.t(),
          :put => OpenApi.V2.Model.Operation.t(),
          :post => OpenApi.V2.Model.Operation.t(),
          :delete => OpenApi.V2.Model.Operation.t(),
          :options => OpenApi.V2.Model.Operation.t(),
          :head => OpenApi.V2.Model.Operation.t(),
          :patch => OpenApi.V2.Model.Operation.t(),
          :parameters => OpenApi.V2.Model.Parameter.t()
        }

  field(:"$ref")
  field(:get, as: OpenApi.V2.Model.Operation)
  field(:put, as: OpenApi.V2.Model.Operation)
  field(:post, as: OpenApi.V2.Model.Operation)
  field(:delete, as: OpenApi.V2.Model.Operation)
  field(:options, as: OpenApi.V2.Model.Operation)
  field(:head, as: OpenApi.V2.Model.Operation)
  field(:patch, as: OpenApi.V2.Model.Operation)
  field(:parameters, as: OpenApi.V2.Model.Parameter)
end

defimpl Poison.Decoder, for: OpenApi.V2.Model.PathItem do
  def decode(value, options) do
    OpenApi.V2.Model.PathItem.decode(value, options)
  end
end

defimpl Poison.Encoder, for: OpenApi.V2.Model.PathItem do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
