# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule OpenApi.V2.Model.Schema do
  @moduledoc """


  ## Attributes

  - $ref (String.t):  Defaults to: `null`.
  - type (String.t):  Defaults to: `null`.
  - format (String.t):  Defaults to: `null`.
  - title (String.t):  Defaults to: `null`.
  - description (String.t):  Defaults to: `null`.
  - default (String.t):  Defaults to: `null`.
  - items (Items):  Defaults to: `null`.
  - collectionFormat (String.t):  Defaults to: `null`.
  - maximum (float()):  Defaults to: `null`.
  - exclusiveMaximum (boolean()):  Defaults to: `null`.
  - minimum (float()):  Defaults to: `null`.
  - exclusiveMinimum (boolean()):  Defaults to: `null`.
  - maxLength (integer()):  Defaults to: `null`.
  - minLength (integer()):  Defaults to: `null`.
  - pattern (String.t):  Defaults to: `null`.
  - maxItems (integer()):  Defaults to: `null`.
  - minItems (integer()):  Defaults to: `null`.
  - uniqueItems (boolean()):  Defaults to: `null`.
  - required (boolean()):  Defaults to: `null`.
  - enum ([String.t]):  Defaults to: `null`.
  - multipleOf (float()):  Defaults to: `null`.
  - allOf (String.t):  Defaults to: `null`.
  - properties (String.t):  Defaults to: `null`.
  - additionalProperties (String.t):  Defaults to: `null`.
  - discriminator (String.t):  Defaults to: `null`.
  - readOnly (boolean()):  Defaults to: `null`.
  - xml (Xml):  Defaults to: `null`.
  - externalDocs (ExternalDocumentation):  Defaults to: `null`.
  - example (String.t):  Defaults to: `null`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :"$ref" => any(),
          :type => any(),
          :format => any(),
          :title => any(),
          :description => any(),
          :default => any(),
          :items => OpenApi.V2.Model.Items.t(),
          :collectionFormat => any(),
          :maximum => any(),
          :exclusiveMaximum => any(),
          :minimum => any(),
          :exclusiveMinimum => any(),
          :maxLength => any(),
          :minLength => any(),
          :pattern => any(),
          :maxItems => any(),
          :minItems => any(),
          :uniqueItems => any(),
          :required => any(),
          :enum => list(any()),
          :multipleOf => any(),
          :allOf => any(),
          :properties => any(),
          :additionalProperties => any(),
          :discriminator => any(),
          :readOnly => any(),
          :xml => OpenApi.V2.Model.Xml.t(),
          :externalDocs => OpenApi.V2.Model.ExternalDocumentation.t(),
          :example => any()
        }

  field(:"$ref")
  field(:type)
  field(:format)
  field(:title)
  field(:description)
  field(:default)
  field(:items, as: OpenApi.V2.Model.Items)
  field(:collectionFormat)
  field(:maximum)
  field(:exclusiveMaximum)
  field(:minimum)
  field(:exclusiveMinimum)
  field(:maxLength)
  field(:minLength)
  field(:pattern)
  field(:maxItems)
  field(:minItems)
  field(:uniqueItems)
  field(:required)
  field(:enum, type: :list)
  field(:multipleOf)
  field(:allOf)
  field(:properties)
  field(:additionalProperties)
  field(:discriminator)
  field(:readOnly)
  field(:xml, as: OpenApi.V2.Model.Xml)
  field(:externalDocs, as: OpenApi.V2.Model.ExternalDocumentation)
  field(:example)
end

defimpl Poison.Decoder, for: OpenApi.V2.Model.Schema do
  def decode(value, options) do
    OpenApi.V2.Model.Schema.decode(value, options)
  end
end

defimpl Poison.Encoder, for: OpenApi.V2.Model.Schema do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
