# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule OpenApi.V2.Model.SecurityScheme do
  @moduledoc """


  ## Attributes

  - type (String.t):  Defaults to: `null`.
  - description (String.t):  Defaults to: `null`.
  - name (String.t):  Defaults to: `null`.
  - in (String.t):  Defaults to: `null`.
  - flow (String.t):  Defaults to: `null`.
  - authorizationUrl (String.t):  Defaults to: `null`.
  - tokenUrl (String.t):  Defaults to: `null`.
  - scopes (Scopes):  Defaults to: `null`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :type => any(),
          :description => any(),
          :name => any(),
          :in => any(),
          :flow => any(),
          :authorizationUrl => any(),
          :tokenUrl => any(),
          :scopes => OpenApi.V2.Model.Scopes.t()
        }

  field(:type)
  field(:description)
  field(:name)
  field(:in)
  field(:flow)
  field(:authorizationUrl)
  field(:tokenUrl)
  field(:scopes, as: OpenApi.V2.Model.Scopes)
end

defimpl Poison.Decoder, for: OpenApi.V2.Model.SecurityScheme do
  def decode(value, options) do
    OpenApi.V2.Model.SecurityScheme.decode(value, options)
  end
end

defimpl Poison.Encoder, for: OpenApi.V2.Model.SecurityScheme do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
