# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule OpenApi.V2.Model.Swagger do
  @moduledoc """


  ## Attributes

  - swagger (String.t):  Defaults to: `null`.
  - info (Info):  Defaults to: `null`.
  - host (String.t):  Defaults to: `null`.
  - basePath (String.t):  Defaults to: `null`.
  - schemes ([String.t]):  Defaults to: `null`.
  - consumes ([String.t]):  Defaults to: `null`.
  - produces ([String.t]):  Defaults to: `null`.
  - paths (Paths):  Defaults to: `null`.
  - definitions (Definitions):  Defaults to: `null`.
  - responses (ResponsesDefinitions):  Defaults to: `null`.
  - securityDefinitions (SecurityDefinitions):  Defaults to: `null`.
  - security ([SecurityRequirement]):  Defaults to: `null`.
  - tags ([Tag]):  Defaults to: `null`.
  - externalDocs (ExternalDocumentation):  Defaults to: `null`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :swagger => any(),
          :info => OpenApi.V2.Model.Info.t(),
          :host => any(),
          :basePath => any(),
          :schemes => list(any()),
          :consumes => list(any()),
          :produces => list(any()),
          :paths => OpenApi.V2.Model.Paths.t(),
          :definitions => OpenApi.V2.Model.Definitions.t(),
          :responses => OpenApi.V2.Model.ResponsesDefinitions.t(),
          :securityDefinitions => OpenApi.V2.Model.SecurityDefinitions.t(),
          :security => list(OpenApi.V2.Model.SecurityRequirement.t()),
          :tags => list(OpenApi.V2.Model.Tag.t()),
          :externalDocs => OpenApi.V2.Model.ExternalDocumentation.t()
        }

  field(:swagger)
  field(:info, as: OpenApi.V2.Model.Info)
  field(:host)
  field(:basePath)
  field(:schemes, type: :list)
  field(:consumes, type: :list)
  field(:produces, type: :list)
  field(:paths, as: OpenApi.V2.Model.Paths)
  field(:definitions, as: OpenApi.V2.Model.Definitions)
  field(:responses, as: OpenApi.V2.Model.ResponsesDefinitions)
  field(:securityDefinitions, as: OpenApi.V2.Model.SecurityDefinitions)
  field(:security, as: OpenApi.V2.Model.SecurityRequirement, type: :list)
  field(:tags, as: OpenApi.V2.Model.Tag, type: :list)
  field(:externalDocs, as: OpenApi.V2.Model.ExternalDocumentation)
end

defimpl Poison.Decoder, for: OpenApi.V2.Model.Swagger do
  def decode(value, options) do
    OpenApi.V2.Model.Swagger.decode(value, options)
  end
end

defimpl Poison.Encoder, for: OpenApi.V2.Model.Swagger do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
