# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Gmail.V1.Model.Thread do
  @moduledoc """
  A collection of messages representing a conversation.

  ## Attributes

  - historyId (String.t): The ID of the last history record that modified this thread. Defaults to: `null`.
  - id (String.t): The unique ID of the thread. Defaults to: `null`.
  - messages ([Message]): The list of messages in the thread. Defaults to: `null`.
  - snippet (String.t): A short part of the message text. Defaults to: `null`.
  """

  defstruct [
    :historyId,
    :id,
    :messages,
    :snippet
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Gmail.V1.Model.Thread do
  import GoogleApi.Gmail.V1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:messages, :list, GoogleApi.Gmail.V1.Model.Message, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Gmail.V1.Model.Thread do
  def encode(value, options) do
    GoogleApi.Gmail.V1.Deserializer.serialize_non_nil(value, options)
  end
end
