# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Gmail.V1.Model.VacationSettings do
  @moduledoc """
  Vacation auto-reply settings for an account. These settings correspond to the \&quot;Vacation responder\&quot; feature in the web interface.

  ## Attributes

  - enableAutoReply (boolean()): Flag that controls whether Gmail automatically replies to messages. Defaults to: `null`.
  - endTime (String.t): An optional end time for sending auto-replies (epoch ms). When this is specified, Gmail will automatically reply only to messages that it receives before the end time. If both startTime and endTime are specified, startTime must precede endTime. Defaults to: `null`.
  - responseBodyHtml (String.t): Response body in HTML format. Gmail will sanitize the HTML before storing it. Defaults to: `null`.
  - responseBodyPlainText (String.t): Response body in plain text format. Defaults to: `null`.
  - responseSubject (String.t): Optional text to prepend to the subject line in vacation responses. In order to enable auto-replies, either the response subject or the response body must be nonempty. Defaults to: `null`.
  - restrictToContacts (boolean()): Flag that determines whether responses are sent to recipients who are not in the user&#39;s list of contacts. Defaults to: `null`.
  - restrictToDomain (boolean()): Flag that determines whether responses are sent to recipients who are outside of the user&#39;s domain. This feature is only available for G Suite users. Defaults to: `null`.
  - startTime (String.t): An optional start time for sending auto-replies (epoch ms). When this is specified, Gmail will automatically reply only to messages that it receives after the start time. If both startTime and endTime are specified, startTime must precede endTime. Defaults to: `null`.
  """

  defstruct [
    :enableAutoReply,
    :endTime,
    :responseBodyHtml,
    :responseBodyPlainText,
    :responseSubject,
    :restrictToContacts,
    :restrictToDomain,
    :startTime
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Gmail.V1.Model.VacationSettings do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.Gmail.V1.Model.VacationSettings do
  def encode(value, options) do
    GoogleApi.Gmail.V1.Deserializer.serialize_non_nil(value, options)
  end
end
